import { CSSProperties } from "../css_types";
declare const Li_base: CSSProperties;
declare const Li_active: CSSProperties;
declare const Li_disabled: CSSProperties;
declare const Ul_base: CSSProperties;
declare const Input: CSSProperties;
declare const Input_disabled: CSSProperties;
declare const Input_active: CSSProperties;
declare const Text: CSSProperties;
declare const Title: CSSProperties;
export { Li_base, Li_active, Li_disabled, Ul_base, Text, Input, Input_disabled, Input_active, Title };
