import { ICSSProperties } from "../css_types";
declare const LiBase: ICSSProperties;
declare const LiActive: ICSSProperties;
declare const LiDisabled: ICSSProperties;
declare const UlBase: ICSSProperties;
declare const Input: ICSSProperties;
declare const InputDisabled: ICSSProperties;
declare const InputActive: ICSSProperties;
declare const Text: ICSSProperties;
declare const Title: ICSSProperties;
export { LiBase, LiActive, LiDisabled, UlBase, Text, Input, InputDisabled, InputActive, Title };
