import { CSSProperties } from '../css_types';
declare const li_base: CSSProperties;
declare const li_active: CSSProperties;
declare const li_disabled: CSSProperties;
declare const base: CSSProperties;
declare const input: CSSProperties;
declare const input_disabled: CSSProperties;
declare const input_active: CSSProperties;
declare const text: CSSProperties;
declare const title: CSSProperties;
export { li_base, li_active, li_disabled, base, text, input, input_disabled, input_active, title };
